### PR TITLE
Update to react@15

### PR DESCRIPTION
**Pull request by choffmeister**
Also updated to babel@6 (react-devtools submodule has updated, too).

### CODE REVIEW

**Comment by bruderstein** [comment]
I'm pretty sure we can drop the peerDep on all 3 react modules (react, react-dom and react-addons-test-utils), as they're not actually needed to use this. They remain dev dependencies however. 

That should make it a patch release :)

**Comment by choffmeister** [comment]
Let me try this...

**Comment by choffmeister** [comment]
So. Now remains to merge this, update dependencies in `unexpected-react` to this and `unexpected-htmllike-jsx-adapter` and release all three. Then everything is 100% react@15 :octocat: :)

**Comment by bruderstein** [comment]
I'm just doing unexpected-htmllike-jsx-adapter, but that can have it's peerDeps on react-dom and react-addons-test-utils also removed.  Can you do that for this PR, then we can have a clean merge?

**Comment by choffmeister** [comment]
You mean removing the peerDeps to react in this repository? That is already pushed.

**Comment by bruderstein** [comment]
D'Oh, sorry! Not at my fittest at the moment.

**Comment by choffmeister** [comment]
:)

**Pull request merged**
