### PR TITLE
Upgrade react-devtools

### PR DESCRIPTION
**Pull request by albertfdp**
Upgrades react-devtools to the latest commit.

### CODE REVIEW

**Comment by bruderstein** [comment]
Great. I needed to add `semver` as a dependency to get this to work, but it fixes the tests thereafter for React 16.5.0

**Comment by bruderstein** [comment]
I'll merge this and add the dependency.

**Comment by bruderstein** [comment]
Thanks ever so much for this - I've bumped the versions all the way up the chain to unexpected-react@5.0.2

**Comment by albertfdp** [comment]
Thank you!

**Pull request merged**
